name: CD Pipeline - Deploy to Azure VM

on:
  workflow_run:
    workflows: ["CI Pipeline - Build, Test & Docker Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug host value
        run: |
          echo "Host: ${{ secrets.AZURE_VM_IP }}"
      
      - name: Install Docker
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker azureuser
          sudo systemctl enable docker
          sudo systemctl start docker
   
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}
            echo "Pulling latest Docker image..."
            docker pull $IMAGE
            echo "Stopping old container..."
            docker stop node-app || true
            docker rm node-app || true
            echo "Running new container..."
            docker run -d --name node-app -p 80:3000 $IMAGE
