name: CD Pipeline - Deploy to Azure VM

on:
  workflow_run:
    workflows: ["CI Pipeline - Build, Test & Docker Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug host value
        run: |
          echo "Host: ${{ secrets.AZURE_VM_IP }}"
   
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}
            echo "Pulling latest Docker image..."
            sudo docker pull $IMAGE
            echo "Stopping old container..."
            sudo docker stop node-app || true
            sudo docker rm node-app || true
            echo "Running new container..."
            sudo docker run -d --name node-app -p 80:3000 $IMAGE
